import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./Header/Nav";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
         <div className="flex justify-between items-center w-full">
          <Nav></Nav>
          <header className="flex justify-end items-center p-4 gap-4 h-16 w-[20%]">
            <Show when="signed-out">
              {/* <SignInButton /> */}
              <SignUpButton>
                <button className="bg-[#426eb5] text-white rounded-[3px] font-medium text-sm sm:text-base h-10 sm:h-12 px-10 sm:px-5 cursor-pointer">
                  Register Now
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
         </div>
         
          {children}
        </ClerkProvider>
        </body>
    </html>
  );
}
